[book]
authors = ["KT_NG3"]
language = "en"
multilingual = false
src = "src"
title = "@valapi Documentation"
description = "Valorant API wrapper for nodejs"

[build]
build-dir = "docs"
create-missing = false

[output.html]
git-repository-url = "https://github.com/valapi"